### ISSUE TITLE
API and site terms

### ISSUE THREAD

**Issue by lukechesser** [Chalarangelo/unscrape#3]
Hey folks.

We've been encountering issues with a lot of bots using this to scrape Unsplash and use the photos, which unfortunately is [against the terms and the license of Unsplash](https://unsplash.com/terms).

We make all of the images [available via the API](https://unsplash.com/developers) so that developers can build with the library in a way that's consistent with our contributor's wishes. I'd ask that out of respect for their contributions that you remove this repo from Github. While we love seeing people build things with Unsplash, we have a better and more scalable way for people to build with Unsplash via the API that aligns with the motivations of our community.

Thanks @Chalarangelo.

**Comment by Chalarangelo** [comment]
Hello @lukechesser.

This was originally a tutorial on how to use Python for scraping and is not used in production as far as I know. I will deal with the issue as soon as possible, just give me some time to figure out the best solution for this issue.

**Comment by Chalarangelo** [comment]
As of now, I have removed all the URLs from the code and even updated the README to state that this project should not be executed in any case. Is that clear enough @lukechesser ? If so, I think I will go ahead and archive the project so that it cannot be altered any further.

**Comment by lukechesser** [comment]
Hey @Chalarangelo great thank you, that works. Appreciate your help on this 👍
